version: '2.1'

services:
  echosampleapp:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 80:8080
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect index.js